In [1]:
import cv2
import torch
from torch import nn
from torchvision import transforms


In [2]:
model = torch.load('EmotionClassificationCNN.2100')

In [3]:
video_capture = cv2.VideoCapture(r'Jojo Rabbit - Gestapo Scene (Heil Hitler).mp4')


In [4]:
ret, frame = video_capture.read()

In [5]:
frame.shape

(720, 1280, 3)

In [6]:
cascade_classifier = cv2.CascadeClassifier(r'haarcascade/haarcascade_frontalface_default.xml')

In [47]:
image = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
image.shape

(720, 1280)

In [48]:
faces = cascade_classifier.detectMultiScale(
        image,
        scaleFactor=1.35,
        minNeighbors=4
    )

In [50]:
faces

()

In [9]:
image[]

True

In [ ]:
not len(faces) > 0

In [51]:
while True:
    ret, frame = video_capture.read()

    # Display the resulting frame
    cv2.imshow('Video', frame)

    # faces = cascade_classifier.detectMultiScale(
    #     image,
    #     scaleFactor=1.35,
    #     minNeighbors=4
    # )
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

In [52]:
image = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
faces = cascade_classifier.detectMultiScale(
        image,
        scaleFactor=1.1,
        minNeighbors=3
    )

In [54]:
max_area_face = faces[0]

for face in faces:
    if face[2] * face[3] > max_area_face[2] * max_area_face[3]:
        max_area_face = face

In [58]:
x, y, w, h = max_area_face
max_area_face

array([725, 276, 141, 141], dtype=int32)

In [ ]:
cv2.imshow('Vide2o', image)

In [17]:
faces


array([[ 752,   16,  116,  116],
       [1020,  252,   99,   99],
       [ 844,  274,   92,   92],
       [ 348,  351,   79,   79],
       [ 207,  350,   90,   90]], dtype=int32)

In [35]:
max_area_face = faces[0]
max_area_face

array([752,  16, 116, 116], dtype=int32)

In [39]:
max_area_face[2] * max_area_face[3]

13456

In [40]:
max_area_face[2] * max_area_face[3]

13456

In [41]:
thunderstorm = torch.load('EmotionClassificationCNN.4500')


In [46]:
thunderstorm.class_to_idx.items()

dict_items([('angry', 0), ('disgust', 1), ('fear', 2), ('happy', 3), ('neutral', 4), ('sad', 5), ('surpise', 6)])